model: nat_base
lr: 1e-5
warmup_lr: 1e-7
min_lr: 5e-7
epochs: 15
cooldown_epochs: 2
warmup_epochs: 2
amp: True
batch_size: 32
sched: cosine
sched_epochwise: False
weight_decay: 5e-2
num_classes: 1
bce_target_thresh: 0.5