model: nat_small
lr: 1e-3
warmup_lr: 1e-6
min_lr: 5e-6
epochs: 12
cooldown_epochs: 2
warmup_epochs: 2
amp: True
batch_size: 32
sched: cosine
sched_epochwise: False
weight_decay: 5e-2
num_classes: 1
bce_target_thresh: 0.5